### PR TITLE
Add relaxed float to int conversions

### PR DESCRIPTION
**Pull request by ngzhian**
For #21.

### CODE REVIEW

**Comment by lars-t-hansen** [comment]
Since these instructions don't saturate, should "sat" really be in the name?

**Comment by ngzhian** [comment]
I was thinking of that too, I chose to keep it to reflect that these instructions are relaxed version of the respective SIMD instructions. The names are not fixed, I hope to be able to discuss them more and get suggestions.

**Comment by ngzhian** [comment]
I changed the name and added a note indicate which instructions they are the relaxed version of.

**Review by lars-t-hansen — APPROVED** [review]
LGTM.

**Pull request merged**
