### PR TITLE
Add description of categories of instructions

### PR DESCRIPTION
**Pull request by ngzhian**

### CODE REVIEW

**Comment by ngzhian** [comment]
@zeux fyi

**Comment by Maratyszcza** [comment]
We may have one more class of instructions: floating-point reductions, where the reduction tree (i.e. order in which individual elements are reduced) is architecture-specific.

**Comment by Maratyszcza** [comment]
And lane-wise select is another a category of its own

**Comment by ngzhian** [comment]
> We may have one more class of instructions: floating-point reductions, where the reduction tree (i.e. order in which individual elements are reduced) is architecture-specific.

What is an example of this? I'll add it to the description with an example.

> And lane-wise select is another a category of its own

This can fall into the first category, integer instructions, couldn't it? Any specific examples you're thinking of?

**Comment by nemequ** [comment]
> What is an example of this? I'll add it to the description with an example.

SVE comes to mind; they have separate instructions for left-to-right reductions and tree-based reductions.  For example, ADDA for left-to-right addition, and ADDV for tree-based addition.  See § 6.17 of the current [Arm C Language Extensions for SVE](https://developer.arm.com/documentation/100987/0000).

**Comment by zeux** [comment]
FWIW in my categorization the order-based differences wrt floating point behavior would just be category 3 - I'm not sure if it makes sense for us to standardize behavior as e.g. "either left-to-right or right-to-left accumulation" as opposed to "accumulation order is unspecified and as such the result may differ due to unspecified number and order of internal rounding operations".

**Comment by Maratyszcza** [comment]
> What is an example of this? I'll add it to the description with an example.

Sum-reduction of a vector of 4 floats could be `(v[0] + v[1]) + (v[2] + v[3])` or `(v[0] + v[2]) + (v[1] + v[3])`.

> FWIW in my categorization the order-based differences wrt floating point behavior would just be category 3

IMO accumulation order differs is not the same as precision differs. Unlikely precision, we can't say which accumulation order is better or worse, yet differences in accumulation order prevent bit-exact reproducibility across platforms.

**Comment by ngzhian** [comment]
> Unlikely precision, we can't say which accumulation order is better or worse, yet differences in accumulation order prevent bit-exact reproducibility across platforms.

Can we add on to category 3 to say "where the precision or order of operations differs"? I can see how they are different, but they don't look different enough to be its own section (contrast this with category 1 and 2.) And we can certainly revisit this categorization as we add more instructions :)

**Comment by zeux** [comment]
> Unlikely precision, we can't say which accumulation order is better or worse

I would almost argue that in qfma it's not clear whether an extra rounding is better or worse as long as it's equally fast ;) eliminating rounding improves precision but makes it harder to use qfma as a blanket replacement (some GPU hardware has fused multiply-add with and without internal rounding for this reason!). So for me I think the general moniker is just "result doesn't have guaranteed precision and can be off by <X>".

(when we talk about various reciprocal estimates for example, I think we'll have a discussion about what degree of difference is acceptable and whether we expect the engine to do any NR refinement by itself on any platform to get closer wrt precision without guaranteeing that the estimates align exactly between the architectures)

**Review by Maratyszcza — APPROVED** [review]

**Pull request merged**
